### PR TITLE
Create README.md :ramen:

### PR DESCRIPTION
**Pull request by Jameskmonger**

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Hurry up and merge me @jamesrichford :hocho:

**Comment by jamesadarich** [comment]
No more ramen? ;P what you doing on github at half midnight on a Saturday?

**Comment by Jameskmonger** [comment]
Oops, sorry if I woke you up! Forgot about your email notifications :no_mobile_phones:

**Comment by jamesadarich** [comment]
Haha no worries wasn't sleeping, would have been my fault for leaving it on anyway :) we need a team project I think loving github at the moment and would be ace!!!

**Comment by Jameskmonger** [comment]
I'm up for that, will talk to you tomorrow about it @jamesrichford

**Comment by jamesadarich** [comment]
Nice!

**Pull request closed without merging**
